/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: RandyGF (https://sketchfab.com/RandyGF)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cloud-3a76eb255e3c4c0199bbfedb2b54342f
Title: Cloud
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cloud_1_4(props) {
  const { nodes, materials } = useGLTF('./models/background/loading/cloud/scene.gltf')
  return (
    <group {...props} dispose={null} scale ={3} position = {[-23,0,-130]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Cloud}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.Cloud}
      />
    </group>
  )
}

useGLTF.preload('./models/background/loading/cloud/scene.gltf')
