/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: tamminen (https://sketchfab.com/tamminen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/volume-cloud-b32d9180ae3440969c9d774993cbfeb1
Title: Volume Cloud
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cloud_4(props) {
  const { nodes, materials } = useGLTF('./models/background/loading/cloud_4/scene.gltf')
  return (
    <group {...props} dispose={null} scale ={0.06} position={[-20,20,-200]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.cloud}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.cloud}
      />
    </group>
  )
}

useGLTF.preload('./models/background/loading/cloud_4/scene.gltf')
