/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Оrрндп ЯТG (https://sketchfab.com/orphanrtg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/manhole-cover-on-broken-asphalt-road-76ee7713e406448384a4fdbf6dee2bd1
Title: Manhole cover on broken asphalt road
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PortHole_2(props) {
  const { nodes, materials } = useGLTF('./models/porthole_2/scene.gltf')
  return (
    <group {...props} dispose={null} >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.065}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.kanal_kanal_u1_v1_0.geometry}
            material={materials.kanal_u1_v1}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/porthole_2/scene.gltf')

