/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: frag112 (https://sketchfab.com/frag112)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/asphalt-broken-road-debris-cracks-40d1dac8aa61404497a5e48c2fbab010
Title: Asphalt broken road debris cracks
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PortHole_4(props) {
  const { nodes, materials } = useGLTF('./models/porthole_4/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.main}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.main}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/porthole_4/scene.gltf')

