/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: burindunsmor (https://sketchfab.com/burindunsmor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/broken-asphalt-a44df945620e41b29ba3a731d75c9079
Title: Broken Asphalt
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PortHole_1(props) {
  const { nodes, materials } = useGLTF('./models/porthole_1/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.broken_asphalt_sketchfab2_Material_u1_v1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.broken_asphalt_sketchfab2_Material_u1_v1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.broken_asphalt_sketchfab2_Material_u1_v1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.broken_asphalt_sketchfab2_Material_u1_v1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.broken_asphalt_sketchfab2_Material_u1_v1}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/porthole_1/scene.gltf')