/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: mobydog (https://sketchfab.com/mobydog)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/posthole-8c75e761d6244e2f9482b0a5009061bd
Title: Posthole
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'

export function PortHole_7(props) {

  const { nodes, materials } = useGLTF('./models/porthole_7/scene.gltf')
  return (
    <group {...props} dispose={null} scale={1.25} position = {[1.9,-8.2,16]}>
      <group rotation={[-Math.PI / 2, 0, -0.3]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials['1665661198867_0']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials['1665661198867_1']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/porthole_7/scene.gltf')
