/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Kidney_02 (https://sketchfab.com/Kidney02)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/photoscan-pothole-1-433a22edfcb749e8b358d778fcb2ecfc
Title: Photoscan - Pothole 1
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PortHole_3(props) {
  const { nodes, materials } = useGLTF('./models/porthole_3/scene.gltf')
  return (
    <group {...props} dispose={null} >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.065}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials['1001.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials['1001.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials['1001.004']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/porthole_3/scene.gltf')
