/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sara Carena (https://sketchfab.com/saracarena1)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/dry-riverbed-spain-6b596a7736c34938b1979e57288a0145
Title: Dry riverbed, Spain
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PortHole_5_2(props) {
  const { nodes, materials } = useGLTF('./models/porthole_5/scene.gltf')
  return (
    <group {...props} dispose={null} scale={0.02} position={[1.4,-8.9,17.5]}>
      <group position={[-0.021, 0.422, 5.9]} rotation={[2.235, -0.061, 0.033]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Model_material2_0.geometry}
            material={materials.material2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Model_material2_0_1.geometry}
            material={materials.material2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Model_material2_0_2.geometry}
            material={materials.material2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Model_material0_0.geometry}
            material={materials.material0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Model_material0_0_1.geometry}
            material={materials.material0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Model_material0_0_2.geometry}
            material={materials.material0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Model_material1_0.geometry}
            material={materials.material1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Model_material1_0_1.geometry}
            material={materials.material1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Model_material1_0_2.geometry}
            material={materials.material1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Model_material3_0.geometry}
            material={materials.material3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Model_material3_0_1.geometry}
            material={materials.material3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Model_material3_0_2.geometry}
            material={materials.material3}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/porthole_5/scene.gltf')

