/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: CombatCarl03 (https://sketchfab.com/CombatCarl03)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fnaf-security-breach-clean-bot-a636ca9c755b471089f24beb813af410
Title: FNaF: Security Breach Clean-Bot
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Robot_3(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/robot_3/scene.gltf')
  const { actions } = useAnimations(animations, group)

   useEffect(() => {

    if (actions) {
        const action = actions[Object.keys(actions)[0]];
        action.setEffectiveTimeScale(0.4); // 속도 줄이기
        action.play();

        const timer = setTimeout(() => {
          action.paused = true;
        }, 15000); // action 멈추기 18초 뒤..
        
        // clean up on unmount
        return () => {
            action.stop();
        };
    }
   }, [actions]);




  return (
    <group ref={group} {...props} dispose={null} scale={0.03} position={[-6.8,-9,-4]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="de6203afeab343fa991b59dfc55564a3fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Mesh" rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
                <group name="CleanBot" rotation={[-Math.PI / 2, 0, Math.PI]} scale={100}>
                  <group name="Object_6">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_9"
                      geometry={nodes.Object_9.geometry}
                      material={materials.CleanBot_Material}
                      skeleton={nodes.Object_9.skeleton}
                    />
                    <group name="Object_8" rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/robot_3/scene.gltf')
