/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: vmatthew (https://sketchfab.com/vmatthew)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/street-asset-pack-f3eb47d02e2e4ab290e66752fa354b48
Title: Street Asset Pack
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function RubberCone(props) {
  const { nodes, materials } = useGLTF('./models/street_asset/scene.gltf')
  return (
    <group {...props} dispose={null} position={[-3.3,-9,16] }>
      <group scale={0.009}>

{/* 1번 라바콘 */}
        <group
          position={[110, 13.829, 80]}
          rotation={[-Math.PI / 2, 0, -2.797]}
          scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cone_Cone_0.geometry}
            material={materials.Cone}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cone_Cone_Base_0.geometry}
            material={materials.Cone_Base}
          />
        </group>

{/* 2번 라바콘 */}
        <group
          position={[230, 13.829, -260]}
          rotation={[-Math.PI / 2, 0, -2.797]}
          scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cone_Cone_0.geometry}
            material={materials.Cone}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cone_Cone_Base_0.geometry}
            material={materials.Cone_Base}
          />
        </group>

{/* 3번 라바콘 */}
        <group
          position={[250, 13.829, 370]}
          rotation={[-Math.PI / 2, 0, -2.797]}
          scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cone_Cone_0.geometry}
            material={materials.Cone}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cone_Cone_Base_0.geometry}
            material={materials.Cone_Base}
          />
        </group>

{/* 4번 라바콘 */}
        <group
          position={[480, 13.829, 480]}
          rotation={[-Math.PI / 2, 0, -2.797]}
          scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cone_Cone_0.geometry}
            material={materials.Cone}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cone_Cone_Base_0.geometry}
            material={materials.Cone_Base}
          />
        </group>


{/* 5번 라바콘 */}
        <group
          position={[480, 13.829, -390]}
          rotation={[-Math.PI / 2, 0, -2.797]}
          scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cone_Cone_0.geometry}
            material={materials.Cone}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cone_Cone_Base_0.geometry}
            material={materials.Cone_Base}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/street_asset/scene.gltf')

