/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: vmatthew (https://sketchfab.com/vmatthew)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/street-asset-pack-f3eb47d02e2e4ab290e66752fa354b48
Title: Street Asset Pack
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function StreetAsset(props) {
  const { nodes, materials } = useGLTF('./models/street_asset/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>

        {/* 위에 두 개가 전체 group */}


    {/* 1. 첫번째 element */}


        {/* 2. 두번쨰 element 라바콘!!!  */}
        <group
          position={[129.611, 13.829, 184.967]}
          rotation={[-Math.PI / 2, 0, -2.797]}
          scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cone_Cone_0.geometry}
            material={materials.Cone}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cone_Cone_Base_0.geometry}
            material={materials.Cone_Base}
          />
        </group>

        {/* 3. 세번째 element */}

        <group position={[1.465, 28.984, -191.693]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.warning_Sign_Pole2_0.geometry}
            material={materials.Sign_Pole2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.warning_Sign2_0.geometry}
            material={materials.Sign2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.warning_Sign_Support2_0.geometry}
            material={materials.Sign_Support2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.warning_Support_Screws2_0.geometry}
            material={materials.Support_Screws2}
          />
        </group>

        {/* 4. 네번째 element  */}


        <group position={[-132.173, 31.254, -222.682]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.give_way_Sign_Pole_0.geometry}
            material={materials.Sign_Pole}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.give_way_Sign_0.geometry}
            material={materials.Sign}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.give_way_Sign_Support_0.geometry}
            material={materials.Sign_Support}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.give_way_Support_Screws_0.geometry}
            material={materials.Support_Screws}
          />
        </group>

        {/* 5. 다섯번째 element  */}
        <group position={[-461.194, 25.967, -210.263]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.stop_Sign_Pole3_0.geometry}
            material={materials.Sign_Pole3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.stop_Sign_Support3_0.geometry}
            material={materials.Sign_Support3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.stop_Support_Screws3_0.geometry}
            material={materials.Support_Screws3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.stop_Stop_Sign_0.geometry}
            material={materials.Stop_Sign}
          />
        </group>

        {/* 6. 여섯번쨰 element */}

        <group position={[-300.739, 27.527, -241.247]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.no_waiting_Sign_Pole4_0.geometry}
            material={materials.Sign_Pole4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.no_waiting_Sign_Support4_0.geometry}
            material={materials.Sign_Support4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.no_waiting_Support_Screws4_0.geometry}
            material={materials.Support_Screws4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.no_waiting_Sign_Circle_0.geometry}
            material={materials.Sign_Circle}
          />
        </group>

        {/* 7 */}
        <group position={[227.297, 14.36, 78.107]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Barrel_Barrel_Base_0.geometry}
            material={materials.Barrel_Base}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Barrel_Barrel_0.geometry}
            material={materials.Barrel}
          />
        </group>

        {/* 8 */}
        <group position={[492.678, 23.118, 52.101]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bin_Bin_0.geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bin_Boards_0.geometry}
            material={materials.Boards}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bin_Lid_0.geometry}
            material={materials.material_32}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bin_Hinge_0.geometry}
            material={materials.Hinge}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.red_barrier_Barrier_0.geometry}
          material={materials.Barrier}
          position={[-191.651, 37.391, 28.434]}
          rotation={[-Math.PI / 2, 0, 0.185]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cardboard_Box_Cardboard_0.geometry}
          material={materials.Cardboard}
          position={[57.186, 12.559, 25.389]}
          rotation={[-Math.PI / 2, 0, -3.139]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metal_barrier1_Metal_Barrier1_0.geometry}
          material={materials.Metal_Barrier1}
          position={[-217.251, 45.488, -72.391]}
          rotation={[-Math.PI / 2, 0, 0.104]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metal_barrier_damaged1_Metal_Barrier1_Damaged_0.geometry}
          material={materials.Metal_Barrier1_Damaged}
          position={[-390.627, 45.508, -149.246]}
          rotation={[-Math.PI / 2, 0, 0.076]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metal_barrier2_Metal_Barrier2_0.geometry}
          material={materials.Metal_Barrier2}
          position={[-389.729, 46.569, 131.216]}
          rotation={[-Math.PI / 2, 0, -0.414]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metal_barrier_damaged2_Metal_Barrier2_Damaged_0.geometry}
          material={materials.Metal_Barrier2_Damaged}
          position={[280.239, 50.584, -210.443]}
          rotation={[-Math.PI / 2, 0, -0.375]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pole_1_pole1_0.geometry}
          material={materials.pole1}
          position={[348.84, 17.502, 101.129]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pole_2_pole2_0.geometry}
          material={materials.pole2}
          position={[394.983, 21.183, 98.885]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Hydrant_Hydrant_0.geometry}
          material={materials.Hydrant}
          position={[484.364, 18.364, 145.391]}
          rotation={[-Math.PI / 2, 0, -0.283]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trashbag_trash1_0.geometry}
          material={materials.trash1}
          position={[244.165, 21.78, 247.265]}
          rotation={[-Math.PI / 2, 0, -0.884]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trashbag2_trash2_0.geometry}
          material={materials.trash2}
          position={[378.754, 11.602, 195.271]}
          rotation={[-Math.PI / 2, 0, -0.184]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cup1_cup1_0.geometry}
          material={materials.cup1}
          position={[449.615, 194.246, 61.317]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cup2_cup2_0.geometry}
          material={materials.cup2}
          position={[464.758, 192.034, 76.767]}
          rotation={[-Math.PI / 2, -1.363, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bottle_bottle1_0.geometry}
          material={materials.bottle1}
          position={[469.894, 201.02, 35.096]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bottle2_bottle2_0.geometry}
          material={materials.bottle2}
          position={[495.515, 195.106, 47.476]}
          rotation={[-Math.PI / 2, 0, 1.217]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shard_shard_0.geometry}
          material={materials.shard}
          position={[481.023, 191.174, 60.054]}
          rotation={[-1.314, -Math.PI / 2, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shard2_shard2_0.geometry}
          material={materials.shard2}
          position={[499.304, 193.734, 67.394]}
          rotation={[0, -0.892, -0.778]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shard3_shard3_0.geometry}
          material={materials.shard3}
          position={[491.99, 190.27, 80.911]}
          rotation={[0.523, -0.348, -0.534]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shard4_shard4_0.geometry}
          material={materials.shard4}
          position={[510.455, 190.478, 70.495]}
          rotation={[0, -0.198, -2.358]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_Cardboard2_0.geometry}
          material={materials.Cardboard2}
          position={[-14.059, 16.349, 156.514]}
          rotation={[-Math.PI / 2, 0, -0.293]}
          scale={100}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/street_asset/scene.gltf')

