/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Lelouch (https://sketchfab.com/severljs)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/road-props-ea361482b06e483f895001407c63794e
Title: Road props
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Tubular(props) {

  const { nodes, materials } = useGLTF('./models/street_asset2/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.03} position={[-3.3,-9,14]}>


       {/*  시선유도봉 컴포넌트 */}
  
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cone2_low_M_road_props_0.geometry}
          material={materials.M_road_props}
          position={[-13, 0.857, -1000]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cone2_low_M_road_props_0.geometry}
          material={materials.M_road_props}
          position={[-13, 0.857, -800]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cone2_low_M_road_props_0.geometry}
          material={materials.M_road_props}
          position={[-13, 0.857, -600]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cone2_low_M_road_props_0.geometry}
          material={materials.M_road_props}
          position={[-13, 0.857, -400]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cone2_low_M_road_props_0.geometry}
          material={materials.M_road_props}
          position={[-13, 0.857, -250]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cone2_low_M_road_props_0.geometry}
          material={materials.M_road_props}
          position={[-13, 0.857, -100]}
        />



      </group>
    </group>
  )
}

useGLTF.preload('./models/street_asset2/scene.gltf')